name: Deploy to Azure App Service - icons-search

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build Next.js app
        working-directory: frontend
        run: npm run build

      - name: Zip artifact for deployment
        working-directory: frontend
        run: zip -r release.zip . -x "node_modules/*" ".git/*" ".next/cache/*" # Exclude unnecessary files

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: icons-search-app
          path: frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: icons-search-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_17732B428DFE45409A33FF8BAAA4466F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69313DF70FA64264A43A6227CFE8310D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_959AAC1628D1480B854E5F8164758D69 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "icons-search"
          slot-name: "Production"
          package: .
