name: Update Fluent UI Icons

on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at 00:00 UTC
  workflow_dispatch: # Allow manual trigger as well

permissions:
  contents: write # Allows GitHub Actions to commit changes

jobs:
  update-icons:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Build
        working-directory: backend
        run: npm run build

      - name: Run update script
        working-directory: backend
        env:
          AZURE_SEARCH_ENDPOINT: ${{ secrets.AZURE_SEARCH_ENDPOINT }}
          AZURE_SEARCH_KEY: ${{ secrets.AZURE_SEARCH_KEY }}
          AZURE_SEARCH_INDEX_NAME: ${{ secrets.AZURE_SEARCH_INDEX_NAME }}
          AZURE_VISION_ENDPOINT: ${{ secrets.AZURE_VISION_ENDPOINT }}
          AZURE_VISION_KEY: ${{ secrets.AZURE_VISION_KEY }}
        run: npm run update-icons:prod

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if file changed
        working-directory: backend
        id: check_changes
        run: |
          if git diff --quiet HEAD -- last_commit; then
            echo "No changes detected. Skipping commit."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "File has changed. Proceeding with commit."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and push file
        working-directory: backend
        if: env.changed == 'true'
        run: |
          git add last_commit
          git commit -m "[GH Action] Auto-update last_commit"
          git push origin main
